from __future__ import annotations

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.mixins import TimestampMixin


class ChatSession(Base, TimestampMixin):
    """One AI Assistant conversation (Phase 8). `session_id` is the
    client-facing opaque string (a UUID, generated by the chat endpoint) —
    kept distinct from the surrogate integer `id` primary key, matching
    every other model in this codebase (Node, Room, etc. all separate a
    business-facing identifier from the DB primary key). No user/auth
    concept is attached — this project has no login system, and Phase 8
    explicitly does not add one."""

    __tablename__ = "chat_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)

    messages: Mapped[list[ChatMessageRecord]] = relationship(
        back_populates="session", cascade="all, delete-orphan", order_by="ChatMessageRecord.id"
    )


class ChatMessageRecord(Base, TimestampMixin):
    """One turn (user or assistant) within a ChatSession. `resolved_location`
    is populated only on assistant turns where a Phase 6 tool actually
    resolved a real location — the same information Phase 7's in-process
    store tracked, now persisted, and used the same way: to let a later
    "how do I get there?" style follow-up resolve without guessing."""

    __tablename__ = "chat_messages"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[int] = mapped_column(
        ForeignKey("chat_sessions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(16), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    resolved_location: Mapped[str | None] = mapped_column(String(150), nullable=True)

    session: Mapped[ChatSession] = relationship(back_populates="messages")
