"""building geo coordinates

Revision ID: 93a0ce5865ca
Revises: cabb26ecec65
Create Date: 2026-08-15 12:45:25.837609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a0ce5865ca'
down_revision: Union[str, Sequence[str], None] = 'cabb26ecec65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'longitude')
    op.drop_column('buildings', 'latitude')
    # ### end Alembic commands ###
