"""cross floor hotspots

Revision ID: 940422ca5804
Revises: e7b2c4f8a1d5
Create Date: 2026-08-01 20:38:10.957651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "940422ca5804"
down_revision: Union[str, Sequence[str], None] = "e7b2c4f8a1d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cross_floor_hotspots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_node_id", sa.Integer(), nullable=False),
        sa.Column("target_node_id", sa.Integer(), nullable=False),
        sa.Column("yaw", sa.Float(), nullable=False),
        sa.Column("pitch", sa.Float(), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cross_floor_hotspots_source_node_id"),
        "cross_floor_hotspots",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cross_floor_hotspots_target_node_id"),
        "cross_floor_hotspots",
        ["target_node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cross_floor_hotspots_target_node_id"), table_name="cross_floor_hotspots")
    op.drop_index(op.f("ix_cross_floor_hotspots_source_node_id"), table_name="cross_floor_hotspots")
    op.drop_table("cross_floor_hotspots")
    # ### end Alembic commands ###
