"""phase5 indoor navigation schema

Revision ID: 94093853d903
Revises: 8810d8202265
Create Date: 2026-07-24 22:14:12.481375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94093853d903'
down_revision: Union[str, Sequence[str], None] = '8810d8202265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Average walking speed used elsewhere (app/navigation/pathfinding.py) — used
# here only to backfill a sane walking_time for edges that predate this column.
AVERAGE_WALK_SPEED_MPS = 1.2

NEW_NODE_TYPES = ["CORRIDOR", "CLASSROOM", "LAB", "OFFICE", "LIBRARY", "CAFETERIA"]


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres enum types can only gain values, and each ADD VALUE must run
    # outside the surrounding migration's implicit transaction on older PG —
    # PG12+ allows it inside a transaction as long as the new value isn't
    # also *used* in that same transaction, which we don't do here.
    for value in NEW_NODE_TYPES:
        op.execute(f"ALTER TYPE node_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE edge_direction AS ENUM ('FORWARD', 'LEFT', 'RIGHT', 'BACK', 'UP', 'DOWN')"
    )
    op.add_column(
        "edges", sa.Column("walking_time", sa.Float(), nullable=False, server_default="0")
    )
    op.add_column(
        "edges",
        sa.Column(
            "direction",
            sa.Enum(
                "FORWARD", "LEFT", "RIGHT", "BACK", "UP", "DOWN",
                name="edge_direction", create_type=False,
            ),
            nullable=False,
            server_default="FORWARD",
        ),
    )
    op.add_column(
        "edges",
        sa.Column(
            "floor_transition", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "edges", sa.Column("accessible", sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column("rooms", sa.Column("department", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # Backfill real values for edges that existed before this migration.
    op.execute(
        f"UPDATE edges SET walking_time = distance / {AVERAGE_WALK_SPEED_MPS} / 60.0 "
        "WHERE walking_time = 0"
    )
    op.execute("UPDATE edges SET floor_transition = TRUE WHERE edge_type IN ('STAIRS', 'ELEVATOR')")
    op.execute("UPDATE edges SET accessible = FALSE WHERE edge_type = 'STAIRS'")

    # Drop the server defaults now that existing rows are backfilled — new
    # rows should go through the application (which always supplies a value).
    op.alter_column("edges", "walking_time", server_default=None)
    op.alter_column("edges", "direction", server_default=None)
    op.alter_column("edges", "floor_transition", server_default=None)
    op.alter_column("edges", "accessible", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "department")
    op.drop_column("edges", "accessible")
    op.drop_column("edges", "floor_transition")
    op.drop_column("edges", "direction")
    op.drop_column("edges", "walking_time")
    op.execute("DROP TYPE IF EXISTS edge_direction")
    # ### end Alembic commands ###

    # Postgres cannot drop individual enum values — downgrading node_type's
    # added labels would require recreating the type entirely, which risks
    # data loss if any node already uses one. Left as a manual step.
