"""fee_information_and_curated_answers

Revision ID: 973c0bc20f50
Revises: 93a0ce5865ca
Create Date: 2026-08-18 18:47:22.041853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973c0bc20f50'
down_revision: Union[str, Sequence[str], None] = '93a0ce5865ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_answers_active'), 'curated_answers', ['active'], unique=False)
    op.create_index(op.f('ix_curated_answers_category'), 'curated_answers', ['category'], unique=False)
    op.create_table('fee_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('quota_category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_document', sa.String(length=200), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_information_academic_year'), 'fee_information', ['academic_year'], unique=False)
    op.create_index(op.f('ix_fee_information_department'), 'fee_information', ['department'], unique=False)
    op.create_index(op.f('ix_fee_information_fee_type'), 'fee_information', ['fee_type'], unique=False)
    op.create_index(op.f('ix_fee_information_program'), 'fee_information', ['program'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_information_program'), table_name='fee_information')
    op.drop_index(op.f('ix_fee_information_fee_type'), table_name='fee_information')
    op.drop_index(op.f('ix_fee_information_department'), table_name='fee_information')
    op.drop_index(op.f('ix_fee_information_academic_year'), table_name='fee_information')
    op.drop_table('fee_information')
    op.drop_index(op.f('ix_curated_answers_category'), table_name='curated_answers')
    op.drop_index(op.f('ix_curated_answers_active'), table_name='curated_answers')
    op.drop_table('curated_answers')
    # ### end Alembic commands ###
